[server]
enableCORS = false
enableXsrfProtection = false
runOnSave = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#3498db"
backgroundColor = "#f5f7fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#2c3e50"
font = "sans-serif"
